# -*- coding: utf-8 -*-
"""Module 3 (sons) et Module 4 (110 virelangues)."""

# Chaque groupe : sons isolés / syllabes / mots / groupes de mots / phrase / phrase rapide
SONS_GROUPES = [
    dict(sons="P / B", isoles="pa – pe – pi – po – pu   |   ba – be – bi – bo – bu",
         syllabes="pa-pa – pe-pe – pi-pi – po-po – pu-pu   |   ba-ba – be-be – bi-bi",
         mots="papa, pipe, bébé, robe, papier, bobine",
         groupes="un petit pain, une belle bague, un beau bébé",
         phrase="Paul prépare plusieurs petits pains pour le petit-déjeuner.",
         rapide="Paul prépare plusieurs petits pains, Paul prépare plusieurs petits pains."),
    dict(sons="T / D", isoles="ta – te – ti – to – tu   |   da – de – di – do – du",
         syllabes="ta-ta – te-te – ti-ti – to-to – tu-tu   |   da-da – de-de – di-di",
         mots="table, toit, tortue, dodu, dindon, danseuse",
         groupes="une tortue têtue, un dindon dodu",
         phrase="Didon dîna, dit-on, du dos d'un dodu dindon.",
         rapide="Didon dîna, dit-on, du dos d'un dodu dindon, Didon dîna, dit-on..."),
    dict(sons="K / G", isoles="ka – ke – ki – ko – ku   |   ga – ge – gi – go – gu",
         syllabes="ka-ka – ke-ke – ki-ki – ko-ko – ku-ku   |   ga-ga – gue-gue – gui-gui",
         mots="cachet, caqueter, gare, gâteau, guitare, kaki",
         groupes="un carquois cassé, un gros gâteau craquant",
         phrase="Combien coûtent ces quinze caisses de kiwis craquants ?",
         rapide="Ces caisses de kiwis craquants coûtent-elles cher, ces caisses de kiwis craquants ?"),
    dict(sons="F / V", isoles="fa – fe – fi – fo – fu   |   va – ve – vi – vo – vu",
         syllabes="fa-fa – fe-fe – fi-fi – fo-fo – fu-fu   |   va-va – ve-ve – vi-vi",
         mots="farine, fauve, veste, voisin, vif, fauve",
         groupes="un fauve vif, une veste violette",
         phrase="Le ver vert va vers le verre vert en verre vert.",
         rapide="Le ver vert va vers le verre vert, le ver vert va vers le verre vert."),
    dict(sons="S / Z", isoles="sa – se – si – so – su   |   za – ze – zi – zo – zu",
         syllabes="sa-sa – se-se – si-si – so-so – su-su   |   za-za – ze-ze – zi-zi",
         mots="saucisson, sûre, cerise, zèbre, azur, gazeuse",
         groupes="six saucissons sûrs, un zèbre zélé",
         phrase="Ces cerises sont si sûres qu'on ne sait pas si c'en sont.",
         rapide="Ces cerises sont si sûres, ces cerises sont si sûres, ces cerises sont si sûres."),
    dict(sons="CH / J", isoles="cha – che – chi – cho – chu   |   ja – je – ji – jo – ju",
         syllabes="cha-cha – che-che – chi-chi – cho-cho – chu-chu   |   ja-ja – je-je – ji-ji",
         mots="chasseur, chaussette, jardin, jaune, jeudi, chouette",
         groupes="un chasseur juché, une chouette jaune",
         phrase="Chouette chose que cette chose chouette, dit le chasseur au chien couchant.",
         rapide="Chouette chose, chose chouette, chouette chose, chose chouette."),
    dict(sons="R", isoles="ra – re – ri – ro – ru – ar – er – ir – or – ur",
         syllabes="ra-ra – re-re – ri-ri – ro-ro – ru-ru – rar – rer – rir",
         mots="rare, roue, rire, robuste, cravate, tracteur",
         groupes="trois rats gris, un rare roseau rouge",
         phrase="Trois gros rats gris rongent trois gros croûtons ronds dans trois gros trous.",
         rapide="Rat vit rôt, rôt tenta rat, rat mit patte à rôt, rôt brûla patte à rat."),
    dict(sons="L", isoles="la – le – li – lo – lu – al – el – il – ol – ul",
         syllabes="la-la – le-le – li-li – lo-lo – lu-lu – lal – lel – lil",
         mots="lilas, livre, lune, salade, village, applaudir",
         groupes="Lili lit un livre, un lilas léger",
         phrase="Que lit Lili sous ces lilas-là ? Lili lit l'Iliade.",
         rapide="Lili lit sous les lilas, Lili lit sous les lilas, Lili lit sous les lilas."),
    dict(sons="M / N", isoles="ma – me – mi – mo – mu   |   na – ne – ni – no – nu",
         syllabes="ma-ma – me-me – mi-mi – mo-mo – mu-mu   |   na-na – ne-ne – ni-ni",
         mots="maman, montagne, nature, nuage, mener, nommer",
         groupes="une montagne nue, un nuage magnifique",
         phrase="Natacha n'attacha pas son chat Pacha, qui s'échappa dans la nature.",
         rapide="Natacha n'attacha pas son chat Pacha, Natacha n'attacha pas son chat Pacha."),
    dict(sons="TR / DR", isoles="tra – tre – tri – tro – tru   |   dra – dre – dri – dro – dru",
         syllabes="tra-tra – tre-tre – tri-tri – tro-tro – tru-tru",
         mots="train, tramway, trottoir, drapeau, dragon, drôle",
         groupes="un train tranquille, un drapeau drôle",
         phrase="Trois tortues trottaient sur trois toits très étroits, tirant un train tranquille.",
         rapide="Trois tortues trottaient sur trois toits, trois tortues trottaient sur trois toits."),
    dict(sons="PR / BR", isoles="pra – pre – pri – pro – pru   |   bra – bre – bri – bro – bru",
         syllabes="pra-pra – pre-pre – pri-pri – pro-pro – pru-pru",
         mots="prendre, prudent, printemps, bras, brosse, brave",
         groupes="un printemps précoce, un bras brave",
         phrase="Le prudent primeur prépare précieusement ses primeurs de printemps.",
         rapide="Le prudent primeur prépare ses primeurs, le prudent primeur prépare ses primeurs."),
    dict(sons="CR / GR", isoles="cra – cre – cri – cro – cru   |   gra – gre – gri – gro – gru",
         syllabes="cra-cra – cre-cre – cri-cri – cro-cro – cru-cru",
         mots="cravate, crocodile, gravier, grand, gris, croquant",
         groupes="un crocodile gris, un gravier croquant sous les pas",
         phrase="Le grand crocodile gris croque un croûton croustillant sur le gravier.",
         rapide="Le grand crocodile gris croque, le grand crocodile gris croque un croûton."),
    dict(sons="CL / GL", isoles="cla – cle – cli – clo – clu   |   gla – gle – gli – glo – glu",
         syllabes="cla-cla – cle-cle – cli-cli – clo-clo – clu-clu",
         mots="clair, cloche, classe, glace, glissade, aigle",
         groupes="une cloche claire, une glace glissante",
         phrase="La cloche claire annonce la classe, sous un ciel clair et glacial.",
         rapide="La cloche claire annonce la classe, la cloche claire annonce la classe."),
    dict(sons="PL / BL", isoles="pla – ple – pli – plo – plu   |   bla – ble – bli – blo – blu",
         syllabes="pla-pla – ple-ple – pli-pli – plo-plo – plu-plu",
         mots="pluie, place, plateau, blanc, bleu, table",
         groupes="un plateau blanc, une place bleue",
         phrase="Sous la pluie, la place blanche devient un plateau bleu et pâle.",
         rapide="Sous la pluie, la place blanche, sous la pluie, la place blanche."),
]

# ---------------------------------------------------------------------------
# MODULE 4 — 110 VIRELANGUES classés par niveau et par son
# ---------------------------------------------------------------------------
# chaque entrée: (texte, son_principal, niveau 1-4)
VIRELANGUES = [
    # Niveau 1 — Facile (courts)
    ("Ton thé t'a-t-il ôté ta toux ?", "T/D", 1),
    ("As-tu été à Tahiti ?", "T", 1),
    ("Suis-je bien chez ce cher Serge ?", "S/CH", 1),
    ("Le loup va vite au bois.", "L/V", 1),
    ("Poisson sans boisson est poison.", "S", 1),
    ("Piano ou violon, voilà mon dilemme.", "P/V", 1),
    ("Douze douches douces dans la salle de bain.", "D", 1),
    ("Seize chaises sèches sèchent au soleil.", "S/CH", 1),
    ("Bonjour Madame, comment allez-vous ce matin ?", "M", 1),
    ("Le chat gris dort sur le tapis.", "CH/R", 1),
    ("Ma tante attend son thé tiède.", "T", 1),
    ("Le petit chat boit son lait blanc.", "L/B", 1),
    ("Ces six sacs sont-ils si lourds ?", "S", 1),
    ("Le facteur porte trois lettres fines.", "F/L", 1),
    ("Un gros chat gris grimpe au grenier.", "GR", 1),
    ("La vache broute dans le pré vert.", "V/R", 1),
    ("Le boulanger vend du bon pain blanc.", "B/P", 1),
    ("Zoé zigzague sur son vélo.", "Z", 1),
    ("Le roi range son royaume avec rigueur.", "R", 1),
    ("Trois pommes tombent du grand pommier.", "P/T", 1),
    ("Le cheval trotte vite dans le champ.", "CH/TR", 1),
    ("Un joli jardin plein de jonquilles jaunes.", "J", 1),
    ("Ma mère aime les mûres mûres.", "M", 1),
    ("Le petit lapin saute dans le pré.", "L/P", 1),
    ("Nadia noue son nœud noir.", "N", 1),
    # Niveau 2 — Intermédiaire
    ("Un chasseur sachant chasser sait chasser sans son chien.", "CH/S", 2),
    ("Les chaussettes de l'archiduchesse sont-elles sèches, archi-sèches ?", "CH/S", 2),
    ("Le juge jugea juste jusqu'à ce que justice soit rendue.", "J", 2),
    ("Panier, piano, panier, piano, panier, piano.", "P/N", 2),
    ("Cinq chiens chassent six chats dans le jardin voisin.", "CH/S", 2),
    ("Tonton, ton thé t'a-t-il ôté ta toux tenace ?", "T", 2),
    ("Gérard j'garde et Gérard je garde le grand jardin.", "G/J", 2),
    ("Zazie causait avec sa cousine en cousant sa jupe.", "Z/S", 2),
    ("L'Arabe Ali arrive, l'Arabe Ali arrive avec ses amis.", "R/L", 2),
    ("Bonjour Madame Sans-Souci, combien sont ces six saucissons-ci ?", "S", 2),
    ("Ce sont seize jacinthes sèches dans le jardin de Cécile.", "S/J", 2),
    ("Le steward alluma une allumette et éteignit six bougies.", "T/S", 2),
    ("Un dragon gradé dégrade un gradé dragon dans son donjon.", "DR/G", 2),
    ("Cinq gros rats gris grignotent six gros grains de riz gris.", "GR/R", 2),
    ("La roue sur la rue roule, la rue sur la roue reste.", "R", 2),
    ("Où niche la pie ? La pie niche haut, l'oie niche bas.", "P/N", 2),
    ("Petit pot de beurre, quand te dépetit-pot-de-beurriseras-tu ?", "P/B", 2),
    ("Le fisc fixe exprès chaque taxe fixe excessive et exquise.", "F/X", 2),
    ("Trois tortues trottaient sur trois toits très étroits et gris.", "TR/T", 2),
    ("Un vieux chevrier plein de vice vend six chèvres vives.", "V/CH", 2),
    ("Fruits frais, fruits frits, fruits cuits, fruits crus, fruits secs.", "FR", 2),
    ("La pipe au papa du pape Pie pue.", "P", 2),
    ("Chasseur, cesse de chasser sans cesse, car à force de chasser sans cesse, tu risques de te lasser.", "CH/S", 2),
    ("Rat vit rôt, rôt tenta rat, rat mit patte à rôt.", "R/T", 2),
    ("Didon dîna, dit-on, du dos d'un dodu dindon.", "D", 2),
    # Niveau 3 — Difficile
    ("Si six scies scient six cyprès, six cent six scies scient six cent six cyprès.", "S/C", 3),
    ("Combien sont ces six saucissons-ci ? Ces six saucissons-ci sont six sous.", "S", 3),
    ("Le chasseur, sachant chasser sans son chien, chassait seul ses six chevreuils.", "CH/S", 3),
    ("Que lit Lili sous ces lilas-là ? Lili lit l'Iliade sous les lilas mauves.", "L", 3),
    ("Trois gros rats gris rongent trois gros croûtons ronds dans trois gros trous ronds.", "R/GR", 3),
    ("Le vin est bon mais le verre est vert, alors le vin dans le verre vert vaut mieux vert.", "V", 3),
    ("Cinq princes prudents prêtent leurs presses précieuses au précédent prince.", "PR", 3),
    ("Le gros grand-père gris gronde le petit grimpeur qui grimpe trop.", "GR", 3),
    ("Un chat vit sept souris sèches sous six sièges cirés.", "CH/S", 3),
    ("La bûcheronne bien bâtie bûcheronne bien avant que le bûcheron ne bûcheronne.", "B", 3),
    ("Trois strates striées se trouvent sous trois strates striées de structures.", "STR", 3),
    ("Cette architecte achète six chaises anciennes chez son ancien architecte.", "CH/T", 3),
    ("Les tenanciers tranchants trient les truites transparentes dans le trou trouble.", "TR", 3),
    ("Le glacier glacé glisse sur la glace glaciale avec grâce et gloire.", "GL/GR", 3),
    ("Ce plieur de plaques bleues plie plusieurs plaques bleues plates par plaisir.", "PL/BL", 3),
    ("Le clou cloue le cadre clair, le clair cadre cloue le clou clair.", "CL", 3),
    ("Cet exquis kaki croquant craque quand ce cuisinier le croque cru.", "K/C", 3),
    ("Ma cousine coud sans cesse ses six chaussettes cousues de soie sombre.", "S/C", 3),
    ("Ce chasseur chanceux chasse chaque jeudi six faisans dans les champs.", "CH/J", 3),
    ("Un âne niais nage naïvement en niant qu'il nage nerveusement.", "N", 3),
    # Niveau 4 — Expert (longs et rapides)
    ("Un chasseur sachant chasser doit savoir chasser sans son chien, car un chasseur qui chasse sans savoir chasser sans son chien n'est pas un bon chasseur.", "CH/S", 4),
    ("Les chaussettes de l'archiduchesse sont-elles sèches, archi-sèches, ou sont-elles archi-sèches, les chaussettes de l'archiduchesse ?", "CH/S", 4),
    ("Si six scies scient six cyprès, six cent six scies scient six cent six cyprès, et si six cent six scies scient six cent six cyprès, six mille six cent six scies scient six mille six cent six cyprès.", "S/C", 4),
    ("Trois tortues trottaient sur trois toits très étroits en tirant trois trains tranquilles et très étranges.", "TR/T", 4),
    ("Le très cru cri du gros gris rat, criant sous le grand pré gras, effraie le petit gars du village grand et proche.", "GR/R", 4),
    ("Didon dîna, dit-on, du dos d'un dodu dindon, dont Didon désirait depuis longtemps déguster le dos dodu.", "D", 4),
    ("Cinq princes prudents prêtent presque toujours leurs presses précieuses aux précédents princes prudents et prévoyants.", "PR", 4),
    ("Ces cerises sont si sûres qu'on ne sait pas si c'en sont, et ces sûres cerises, si elles sont sûres, sont ces cerises-ci.", "S", 4),
    ("Le grand crocodile gris croque un gros croûton croustillant, croustillant croûton que ce grand crocodile gris croque avec grâce.", "CR/GR", 4),
    ("Trois strates striées se trouvent sous trois strates striées de structures trouées, structures trouées que ces strates striées recouvrent.", "STR", 4),
    ("Le glacier glacé glisse avec grâce sur la glace glaciale et glissante, glace glissante que ce glacier glacé traverse chaque jour.", "GL", 4),
    ("Un chat vit sept souris sèches sous six sièges cirés, sièges cirés que ce chat sournois surveille sans cesse chaque soir.", "CH/S", 4),
    ("Ce plieur de plaques bleues plie plusieurs plaques bleues plates par plaisir, plaisir que ce plieur partage avec ses proches chaque printemps.", "PL/BL", 4),
    ("La bûcheronne bien bâtie bûcheronne bien avant que le bûcheron ne bûcheronne, bûcheron que cette bûcheronne bien bâtie dépasse chaque matin.", "B", 4),
    ("Le prudent primeur prépare précieusement ses primeurs de printemps, primeurs précieuses que ce prudent primeur protège avec précision.", "PR", 4),
    # Compléments — Niveau 1
    ("Le petit poisson nage dans le grand bassin bleu.", "P/N", 1),
    ("Ma sœur coud sa jupe avec un joli fil jaune.", "S/J", 1),
    ("Le vieux hibou dort dans le creux du chêne.", "V/CH", 1),
    ("Julie joue du violon près du vieux jardin.", "J/V", 1),
    ("Le train part tôt, très tôt ce matin.", "TR/T", 1),
    # Compléments — Niveau 2
    ("Ce sont seize souris grises qui grignotent six grains gris.", "S/GR", 2),
    ("Le boulanger blond broie du blé blanc dans son grand bol.", "B/L", 2),
    ("Trois chats gris grimpent chaque jour sur trois grands chênes.", "CH/GR", 2),
    ("Le facteur fatigué franchit fièrement le fossé fangeux.", "F", 2),
    ("Notre voisine range ses roses roses dans son vase rond.", "R/N", 2),
    # Compléments — Niveau 3
    ("Ce vieux forgeron forge fièrement un fer fin et fort chaque matin gris.", "F/G", 3),
    ("La cigogne rongée par le froid replonge dans sa cage grise et froide.", "G/R", 3),
    ("Ces douze douches douces dans la salle de bain sentent la lavande douce et fraîche.", "D", 3),
    ("Le jeune juge juge justement chaque jugement jugé jusque-là injuste.", "J", 3),
    ("Notre gracieuse cantatrice chante six chants gracieux chaque jeudi soir chez son professeur.", "CH/S", 3),
]

VIRELANGUE_METHODE = [
    "Étape 1 : très lentement, en articulant chaque syllabe séparément",
    "Étape 2 : lentement, mais sans aucune erreur ni hésitation",
    "Étape 3 : à vitesse normale de conversation",
    "Étape 4 : légèrement plus rapide qu'à l'oral courant",
    "Étape 5 : à vitesse maximale, en gardant la précision",
    "Étape 6 : répéter 3 fois de suite sans erreur à la vitesse choisie",
]
