# -*- coding: utf-8 -*-
"""Module 11 — 100 sujets d'improvisation et Module 12 — 30 simulations."""

SUJETS_IMPRO_FACILE = [
    "Décrivez votre repas préféré et pourquoi vous l'aimez.",
    "Racontez votre trajet habituel jusqu'à votre lieu d'étude ou de travail.",
    "Décrivez une journée de pluie idéale.",
    "Parlez d'un objet que vous utilisez tous les jours.",
    "Racontez votre dernière sortie entre amis.",
    "Décrivez votre saison préférée et pourquoi.",
    "Parlez d'un film ou d'un livre qui vous a marqué.",
    "Décrivez votre quartier à quelqu'un qui ne le connaît pas.",
    "Racontez comment se déroule votre matinée type.",
    "Parlez d'une compétence que vous aimeriez apprendre.",
    "Décrivez votre animal préféré sans le nommer.",
    "Racontez un souvenir de vacances.",
    "Parlez de votre plat préféré à cuisiner.",
    "Décrivez la maison ou l'appartement de vos rêves.",
    "Racontez ce que vous avez fait ce week-end.",
    "Parlez d'une chanson qui vous met de bonne humeur.",
    "Décrivez votre façon idéale de passer une soirée.",
    "Racontez une habitude que vous avez depuis l'enfance.",
    "Parlez de la personne qui vous a le plus inspiré.",
    "Décrivez ce que représente pour vous une bonne journée.",
    "Racontez un projet personnel en cours.",
    "Parlez d'un endroit que vous rêvez de visiter.",
    "Décrivez votre relation avec les réseaux sociaux.",
    "Racontez comment vous organisez votre semaine.",
    "Parlez d'un cadeau qui vous a particulièrement touché.",
]

SUJETS_IMPRO_INTERMEDIAIRE = [
    "Expliquez pourquoi vous avez choisi vos études ou votre métier actuel.",
    "Racontez une difficulté rencontrée dans votre travail et comment vous l'avez surmontée.",
    "Décrivez votre méthode pour gérer le stress avant un examen ou une échéance.",
    "Expliquez comment vous géreriez un désaccord avec un collègue.",
    "Parlez d'un échec qui vous a appris quelque chose d'important.",
    "Décrivez votre équipe idéale de travail.",
    "Expliquez pourquoi la ponctualité est importante ou non selon vous.",
    "Racontez une décision difficile prise récemment dans votre vie professionnelle ou scolaire.",
    "Décrivez ce que vous attendez d'un bon manager ou d'un bon professeur.",
    "Expliquez comment vous équilibrez vie personnelle et vie professionnelle.",
    "Parlez d'une relation qui vous a fait grandir.",
    "Racontez une situation où vous avez dû convaincre quelqu'un.",
    "Décrivez ce que réussir signifie pour vous.",
    "Expliquez comment vous géreriez une critique injuste.",
    "Parlez d'un objectif professionnel que vous poursuivez actuellement.",
    "Racontez une collaboration qui s'est particulièrement bien passée.",
    "Décrivez comment vous géreriez un imprévu de dernière minute au travail.",
    "Expliquez pourquoi vous pensez être fiable dans un travail d'équipe.",
    "Parlez d'un mentor ou d'une personne qui vous a formé.",
    "Racontez comment vous avez géré une charge de travail importante.",
    "Décrivez votre façon de prendre des décisions sous pression.",
    "Expliquez ce que vous feriez si vous n'étiez pas d'accord avec une consigne.",
    "Parlez d'une compétence que vous avez développée récemment.",
    "Racontez une expérience où vous avez dû apprendre vite.",
    "Décrivez comment vous vous adaptez à un nouvel environnement.",
]

SUJETS_IMPRO_AVANCE = [
    "Défendez l'idée que l'échec est plus formateur que le succès.",
    "Convainquez quelqu'un de l'intérêt d'apprendre une nouvelle compétence chaque année.",
    "Défendez l'idée qu'il vaut mieux se spécialiser que d'être généraliste.",
    "Argumentez en faveur du travail en équipe plutôt qu'en solitaire.",
    "Défendez l'idée que la routine peut être une force plutôt qu'une contrainte.",
    "Convainquez un collègue hésitant de rejoindre un nouveau projet.",
    "Défendez l'idée qu'il faut savoir dire non pour être efficace.",
    "Argumentez pour ou contre le télétravail à temps plein.",
    "Défendez l'idée que la préparation compte plus que le talent naturel.",
    "Convainquez un public sceptique de l'utilité d'une nouvelle méthode de travail.",
    "Défendez l'idée que les erreurs doivent être partagées ouvertement en équipe.",
    "Argumentez en faveur d'un rythme de travail plus lent mais plus qualitatif.",
    "Défendez l'idée que la curiosité est la compétence la plus sous-estimée.",
    "Convainquez quelqu'un de sortir de sa zone de confort régulièrement.",
    "Défendez une opinion impopulaire sur l'organisation du travail moderne.",
    "Argumentez pour l'importance de la transparence dans une équipe.",
    "Défendez l'idée que l'expérience compte plus que les diplômes.",
    "Convainquez quelqu'un de l'intérêt de la prise de parole en public.",
    "Défendez l'idée qu'un bon leader doit parfois suivre plutôt que diriger.",
    "Argumentez pour ou contre les réunions systématiques en entreprise.",
    "Défendez l'idée que la simplicité est un signe d'intelligence.",
    "Convainquez un public que le changement est toujours une opportunité.",
    "Défendez l'idée que l'on apprend davantage en enseignant qu'en étudiant seul.",
    "Argumentez en faveur d'objectifs modestes mais tenus plutôt qu'ambitieux mais abandonnés.",
    "Défendez l'idée que le doute est un outil utile plutôt qu'un obstacle.",
]

SUJETS_IMPRO_EXPERT = [
    "On vous demande, sans préavis, de résumer un projet en trente secondes devant la direction.",
    "Un supérieur vous pose une question à laquelle vous n'avez pas la réponse : répondez sans paniquer.",
    "Vous devez annoncer un retard sur un projet à un client mécontent.",
    "On vous demande votre avis sur une décision que vous découvrez à l'instant.",
    "En entretien, on vous demande de parler de votre plus grand échec.",
    "Un recruteur vous demande pourquoi il devrait vous choisir vous plutôt qu'un autre candidat.",
    "On vous interrompt en pleine présentation pour poser une question déstabilisante.",
    "Vous devez justifier une décision impopulaire devant votre équipe.",
    "On vous demande de résumer en une phrase l'intérêt de votre projet.",
    "Un supérieur vous demande votre avis franc sur une méthode que vous n'aimez pas.",
    "Vous devez rassurer une équipe inquiète face à un changement soudain.",
    "On vous pose une question piège en entretien : répondez avec calme et clarté.",
    "Vous devez présenter un résultat décevant tout en restant crédible.",
    "On vous demande, en réunion, de trancher entre deux options en une minute.",
    "Un client vous demande pourquoi le prix a augmenté : répondez avec assurance.",
    "Vous devez répondre à une objection difficile en pleine négociation.",
    "On vous demande d'expliquer une erreur de votre équipe devant la direction.",
    "Un journaliste imaginaire vous pose une question inattendue sur votre projet.",
    "Vous devez motiver une équipe fatiguée avant une échéance importante.",
    "On vous demande de défendre votre position face à un désaccord frontal.",
    "Vous devez répondre calmement à une remarque désobligeante en public.",
    "On vous demande votre avis sur un sujet que vous découvrez à l'instant même.",
    "Vous devez conclure une réunion qui a mal tourné sur une note constructive.",
    "Un supérieur vous demande de vous justifier sur un choix pris dans l'urgence.",
    "Vous devez répondre en direct à une question du public après une présentation.",
]

# ---------------------------------------------------------------------------
# MODULE 12 — 30 simulations réelles
# ---------------------------------------------------------------------------
SIMULATIONS = [
    "Vous rencontrez une personne importante pour la première fois : présentez-vous en 30 secondes.",
    "Vous devez vous présenter devant un nouveau responsable le premier jour d'un poste.",
    "On vous demande de présenter votre projet en 2 minutes, sans support visuel.",
    "On vous demande votre opinion alors que vous n'aviez pas préparé de réponse.",
    "Vous devez expliquer un problème technique ou organisationnel à votre supérieur.",
    "Vous devez défendre votre projet face à des objections en réunion.",
    "Vous répondez à une question difficile en entretien d'embauche.",
    "Vous devez prendre la parole devant un grand groupe (imaginez 50 personnes).",
    "Vous appelez un service client pour résoudre un problème urgent.",
    "Vous devez négocier un délai supplémentaire pour un projet en retard.",
    "Vous présentez les résultats d'un travail d'équipe devant la direction.",
    "Vous devez recadrer poliment un collègue qui ne respecte pas un délai.",
    "Vous répondez à un appel téléphonique inattendu d'un client mécontent.",
    "Vous devez féliciter publiquement un membre de votre équipe de façon sincère.",
    "Vous animez une réunion de dix minutes sur un sujet imposé à l'instant.",
    "Vous devez décliner poliment une proposition sans vexer votre interlocuteur.",
    "Vous vous présentez à un entretien pour un stage ou une alternance.",
    "Vous devez expliquer à un enfant un concept compliqué avec des mots simples.",
    "Vous prenez la parole en dernière minute pour remplacer un collègue absent.",
    "Vous devez annoncer une bonne nouvelle à toute une équipe.",
    "Vous devez annoncer une nouvelle plus délicate à un petit groupe.",
    "Vous participez à un débat contradictoire sur un sujet professionnel.",
    "Vous devez convaincre un investisseur imaginaire en 3 minutes.",
    "Vous répondez, en visioconférence, à une question technique inattendue.",
    "Vous devez gérer une objection pendant une vente ou une présentation.",
    "Vous devez vous excuser professionnellement pour une erreur commise.",
    "Vous accueillez un nouveau membre dans votre équipe et le présentez aux autres.",
    "Vous devez résumer, à la volée, ce qui vient d'être dit lors d'une réunion.",
    "Vous répondez à une question piège d'un examinateur ou d'un jury.",
    "Vous devez clore un échange tendu sur une note professionnelle et posée.",
]
